name: schoolexam
description: Dart package used for the communication with the school exam backend. Can be understood as a package implementing the API requests.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0

  # Provides information about application and cache directories
  path_provider: ^2.0.8

  #
  http: ^0.13.4

  # Configuration for api values etc.
  global_configuration: ^2.0.0-nullsafety.1

  # Used for persisting user secrets
  flutter_secure_storage: ^5.0.2

  # Get token meta data
  jwt_decoder: ^2.0.1

  tuple: ^2.0.0