import 'package:schoolexam/exams/exams.dart';

class DummyExamsRepository extends ExamsRepository {
  const DummyExamsRepository() : super();

  @override
  Future<Exam> getExam(String examId) async {
    var exams = await getExams();

    return exams.firstWhere((element) => element.id == examId,
        orElse: () => Exam.empty);
  }

  @override
  Future<List<Exam>> getExams() async {
    return [
      Exam(
          id: "e001",
          status: ExamStatus.planned,
          title: "Projektmanagement",
          dateOfExam: DateTime.utc(2021, 12, 11),
          dueDate: DateTime.utc(2022, 01, 11),
          topic: "Sozialwissenschaften",
          quota: 0.0,
          participants: [
            Course(id: "c001", displayName: "8a", children: [
              Student(id: "s001", displayName: "Max Mustermann"),
              Student(id: "s002", displayName: "Lars Becker")
            ])
          ],
          tasks: []),
      Exam(
          id: "e002",
          status: ExamStatus.inCorrection,
          title: "Europa L2",
          dateOfExam: DateTime.utc(2021, 11, 15),
          dueDate: DateTime.utc(2021, 12, 15),
          topic: "Sozialwissenschaften",
          quota: 55.0,
          participants: [
            Course(id: "c002", displayName: "9b", children: [
              Student(id: "s001", displayName: "Max Mustermann"),
              Student(id: "s002", displayName: "Lars Becker")
            ])
          ],
          tasks: [
            Task(id: "t001", title: "Aufgabe 1", maxPoints: 5),
            Task(id: "t002", title: "Aufgabe 2", maxPoints: 10),
          ]),
      Exam(
          id: "e003",
          status: ExamStatus.corrected,
          title: "Vokabeltest L1",
          dateOfExam: DateTime.utc(2021, 12, 08),
          dueDate: DateTime.utc(2022, 01, 08),
          topic: "Englisch",
          quota: 100.0,
          participants: [
            Course(id: "c003", displayName: "6a", children: [
              Student(id: "s001", displayName: "Max Mustermann"),
              Student(id: "s002", displayName: "Lars Becker")
            ])
          ],
          tasks: [])
    ];
  }

  @override
  Future<List<Submission>> getSubmissions({required String examId}) async {
    final Exam? exam = (await getExams())
        .firstWhere((element) => element.id == examId, orElse: null);

    if (exam == null) return [];

    final String pdf1 =
        "JVBERi0xLjYNJeLjz9MNCjExIDAgb2JqDTw8L0xpbmVhcml6ZWQgMS9MIDk2ODIvTyAxMy9FIDU1MTcvTiAxL1QgOTM4MC9IIFsgNDYwIDE1MV0+Pg1lbmRvYmoNICAgICAgICAgICAgICAgICAgICAgDQoxOSAwIG9iag08PC9EZWNvZGVQYXJtczw8L0NvbHVtbnMgNC9QcmVkaWN0b3IgMTI+Pi9GaWx0ZXIvRmxhdGVEZWNvZGUvSURbPDQ2ODlCNzBDRDZENjk2NENCMjMxREI5NTY0RkYwRDUxPjw1N0RCODQ3MTg1RUE3NDQxOTI0QzA0NkExQTFFNzQ5Nz5dL0luZGV4WzExIDE1XS9JbmZvIDEwIDAgUi9MZW5ndGggNTgvUHJldiA5MzgxL1Jvb3QgMTIgMCBSL1NpemUgMjYvVHlwZS9YUmVmL1dbMSAyIDFdPj5zdHJlYW0NCmjeYmJkEGBgYmAKBhIMPkCCcRuI1QUkeDNBrAggwTIXSLxRZ2BiZJgNEmNgRCf+M+79AxBgAO0TB+0NCmVuZHN0cmVhbQ1lbmRvYmoNc3RhcnR4cmVmDQowDQolJUVPRg0KICAgICAgICANCjI1IDAgb2JqDTw8L0ZpbHRlci9GbGF0ZURlY29kZS9JIDg4L0xlbmd0aCA2Ny9PIDcyL1MgMzg+PnN0cmVhbQ0KaN5iYGBgY2BgkmAAAqF7DKiAEYhZGDgaFJDE2KCYgSGCgYf1gdFBAQaTgBdQ1aK9UF33wDoZlE9D+bcAAgwASb4I0Q0KZW5kc3RyZWFtDWVuZG9iag0xMiAwIG9iag08PC9NZXRhZGF0YSAyIDAgUi9PdXRsaW5lcyA2IDAgUi9QYWdlcyA5IDAgUi9UeXBlL0NhdGFsb2c+Pg1lbmRvYmoNMTMgMCBvYmoNPDwvQ29udGVudHMgMTQgMCBSL0Nyb3BCb3hbMC4wIDAuMCA2MTIuMCA3OTIuMF0vTWVkaWFCb3hbMC4wIDAuMCA2MTIuMCA3OTIuMF0vUGFyZW50IDkgMCBSL1Jlc291cmNlczw8L0ZvbnQ8PC9DMF8wIDI0IDAgUj4+L1Byb2NTZXRbL1BERi9UZXh0XT4+L1JvdGF0ZSAwL1R5cGUvUGFnZT4+DWVuZG9iag0xNCAwIG9iag08PC9MZW5ndGggODg+PnN0cmVhbQ0KQlQKMCBpIAovUmVsYXRpdmVDb2xvcmltZXRyaWMgcmkKL0MwXzAgMTIgVGYKMTcwLjIzMiA3NjYuODQ2IFRkCjwwMDM1MDA0NjAwNTQwMDU1PlRqCkVUCg0KZW5kc3RyZWFtDWVuZG9iag0xNSAwIG9iag08PC9GaWx0ZXIvRmxhdGVEZWNvZGUvRmlyc3QgMzQvTGVuZ3RoIDMwODEvTiA1L1R5cGUvT2JqU3RtPj5zdHJlYW0NCmjevJlbbxzHEYX/yjxKCITt6nsDBgFdIlgPsRPLsQIM5oGWNvQCFCmQKyD69zlf9azkIDCQpzxwprenL9V1OXWqGcMSlmhLiUuMSwp9iWmpydISs9768t13hx8fPhwfTnc3T958ON6dT+cvTw8/HW9Oj+eHL0+ef7j/9fj08Pbzp0+3x4/6vISrK815/vieH6OPw8s3r94ez4tVbfXT4eX1p++Pp5vfzkstdnh1nOOepRoOr2+vbx6Xenh9f3d+8eL+X+uzOIJ/0uSeWWzzj6+vP55uvzz5y+nudH+3/PXh/unsPt0e02LN96Hjh+uPx8Pffnz5y+uXf5qDNfaZZP98e/3gI96eH47n978dfrh/+Hh9613vpnQ5hMOb8/Xt6f3zu5vb4xIOb8/Hj78sPRx+/vLp6EOR/uH06Xz/cPjHfqicmp//xfXjkSF/vD1q+fKoNd/c/fN+icGlfvVusaCd/3N1LMTXt59/PbO3pjIAOX4nzeHdGtYSZM/YltjqkqxveSlL7mGpayt1aWb6mrahXZaU62K25qAxnVl9SRrj72Sb9Birz2W57v1xrEWuwnDeqY2lFTnMkAf1vtRalpbKUmqXR+mb6XeVINmWpN+1paWkvnSNbznpr2ks77JUnTE3OZ32bUmihrSMZvISHFF/+p00LqX5Llp3HjZL6UPtvmQ5b4m8i0SV8MihuVHvqKNl9UXJ203j2VtaKJpfpJakvVJtigGtnSSL5KpdymtxyWVoTTSGTpK/XWWtbqPJL11NY6xWxib7SbvmXRbimlub7TqWxNCcNabpm4RqWEJKRWkJ4YOE1F8fOhgCSyD9jgkB9Me6OvxorF3dApvpBCaNZTZObR2K5M5mnKQEaXdogqRGizqlawNLKMqbFipoNdu0qs3TtiQr1N3Smn9pz9MzN3vftOw+l/168L4WohzIFIzVvcNaW2vFqfpi3dxDrEf9zb2ty0Fz2qxLMe4dvFGelDUU1LIcXmGD/u4eYVK4vGKLeIH2xgtiqGuOpj5ZStZ1T8DpbfcCK6ssv0XD0YN7QIy2yvJbjIDgtD7KJ4zQhRx/xfpFHojHYcys0IoyWJQ3owcZaOWcQ/OqPLPGNnWIJ/Pb0BlyN3kyhsXwhIgUmnXAKNcrmlwwhHtCcRdNuL2UVCsTpNGhk3RptWFlJKo2P8ifpDfppqHDIKN2eUtXmHZNcQ/TIVrrc30pv7BEQWAtKRSY43AKKQMPlOfxOw5bS9OBhw4qWTsKH1Lo7vhRhuiEnQzQmCMYIKRQZBFu545TVe8nzJMUEGXIUjRH4N7CmA7kY0GjMsNYEeIhiqwVh9R6xXxtdFb1vqznYxiriKI/SxlZ+3cgKHKm6g6A8oGSirEzhisTVgSGJeG8Mm4mmMA+3smNJVyXrHufgifvEOe/2Uv6cpl78t/FgD+iNAyHXQROiQPLU2UUQjsL2/LQbxkgN4C6+zj3MB2ktDzbKBAF1csGbBq3JINkP6x+W1yJ+KRoTaVsWQfPeLmPaStKSsIyG0SOlKUodsxzfJQiJJc8fct4fZqYrUOvHrFyCIyb84zunG2NgrosBeYMVyjAms6T5veSv80Dd0vb+/ucB57K8D6vgvv7us2+zUPJOv/sL3NeQ/ltzmvoYl+392/zgE9FovcLQXweOsVhmYe+xyUKFdnYoAKtnou2EqQbtT2nBa0b5KXd9MEmPPoHm1hNaBfBB8lI7a14AlK7EM2CPCnM20BWt80jImkNkihRmAjmNqNTSq/+Xb8v80CDvHt2TjqM9pCigeyOx2byuhJljC4PWd8NkcvmiVrfyDFFBiG3ky4KkegGmRFYZIyZUIODiUdCleKi9qoATPaoUvSupRNpRCIEgPWK56smaGOunwH4R/bkML8VEAcG4iTBVgHX5tHqqEbK0BmS5O3oaaaGgoMC+XLiMtrqukWHYaYcRfC6E4qtyukrSJH4LiQatlXpC8iFZFSDVFRPKSIXSjND3zVW+gI99EeawbG2CvuFUEBEImhVnZAA5xW0dhsFyat9dT4x5L0P1lwnYQHiFSxOWmTHOuXVO65Ky1tFJtnIQbvCfHJz6Ky5r3IwDRjuILCZWtIqWNmcBUmp5LNayEdZfRpXJxQJwkUi1AfEkue8b8hhQJS6kfdhX7Cf2vIaG9AoYcjPbbKhipF2GK1d+8rpod21V0eK2tvqDEnGqIK7KsPzG8PWEZ1vVGB5dDd+FWyKBziLgs01cjTcIsDumjOqpgirk3ltwOVESilVgdYwhFJNi0B49/TRxEAF51sTVDd3MBhnXHG0RuqS0mdfUfAxrnoeRp6WuuuykaZymH1CMqWdrSnI4EkgbSthFbJsreDIZa5X6ipH2XBsnB80VTpyfkL+J43PPgWanPF3KU7flZObzVTX4DSdlLc1OVnbg6PBpEl70ndTQMwA0drKCJ5SI2/ye/S02EZahfhbE6o1EM37tP+YrBYe0J3YwxKKn7FLpg7KeR+gZp5Su0ERqqfVLmeHHYOYPUoPEM4QnXgm0hxvgj5M28zv3974A+1LReBImmdQEwQAJvr3IG7JfetSDVSNJUhlJ68KPOAJvoL+s1cC7gtlR2f0Kl/snGHnor0mBXhTn4CVWNDcXgFJ+nS2NquVLt136WFIV10Ztfe5Zu9UJ7OC6dLnCOYyjzDHjsZ7sjDvF0DB+dh7CCQGgFB4C5ThtUGHGnKukafgQ+g6yix9hlC5OKG2bQhNByWHBB440V4ydQXaIGgIVJH56nMvCg5TyWSlPFxorQnR3AYFCYRQQDJ6XH0uWWPMA01FF1e0g4aRsZI7zyVFZueepMHhKK/0SXXjpGYSGjXi6jUDiQd/I1EFEmSZNIrpHepExi0uwqRUzasxfJHtfW5wzFrKziQQJzvnpqiKkFpKUK0Ac9a2Qd0JadLke2rooPrueV7pVh0MJoFGhM3+6L6qGjBqkmHwBuvXvK9febRZH+zs2vmGNxjeq59FDa/k+r5D93ou7DtQ+ARSme/g+hqXHYY/6r4DZU0Ylx0oDigjfQdqSaNY9B2Mpcx2qU1WM+q/OTLySGEfmZiHiX0kxZPJcXx3k0r0KHM/84sA6IBvpTTkyjMUZCQMn4KzxjT1aoUZ1Ebo37igodrzCtQEcamolLOGFFS/s7vzgGixWgdbdnfGN4ht3JqYUs4aYKXyQwenu3nCJERIsrPan6w39ema2XMEPthVDytY9ZDnKJjUyH4rAgEkH8OJ3E3hR6QYDuXkFD4RveB3jgQc6VCtzcuGCvxBwOFmwGiY2/J2MSDeSmMWUXxM0ZOwGk7bHO0a9w5pryKhOWT/PrMvmQoEJgsTLfDcRMGxX8vA8zvoI+Ryk8ukwhg4AXjoJY1wzOPBgV4WIitYc64xiL3kB+kiPR2ywhAYlVUd0bz6UpT1odI90gOb5GpGjbZmB4kJRAzzGwNW8+Gaq8du6ig63i5HmnWshgyMshc3RvlokzAYDUnCpaNfCyTjm+0XA8n4FmdqUIMBSvJ+GZAI7+R8iymJbyRxOYgcn9uQnTKpwTcc1nfAYVGuBx85yyA4xUdSIyW/qGJ3tJ1I0r47oe9psHiDkRCexDdO5Klval7fsp+o0OAbF1xMydEfkzCowTc01b2hpWDwxUei/OwXVUZDomNsVzK1VEL3LotXid7dqUb+v/X3H9Xel7qbSxrj9sNKnJRNjeg8zhyq/A5udhenckYRZWUnfUahbVTnbhM9nMcZlZTNMsq7s9Mco5gyqibXNmUTbM5IK3pclszDCZ1xQ2Zey2ANFUb/xd/Mr1gog1CWUQddKJyhFitt5mI12NApHXu18ZXHGSCmx7yftPm9T95mVECQOSNTGhl97+bUY09ClEZ6TPqmRt8PS66oYRpJDeOR3VRGwtVjTPehJtIjzsRNdWT1ondqHaOYcZVRzRgh5SqpqLP6jWemIckgKXM/8kCliPQdylgvsAWf8OuIsl+kBT+DX6xNTUt7lWvM6tmVPeDGY+fbFZ41bRDjfiNSbb8NqfsNSZyA3Ou2XV2pYOWSfPufLt/n/x0+XN+dGffIfz24YP/z3fv7D6e7m8PlPx3Pvv966b7ftt///e6kQcdF/syUr9fvV1f/FmAAdkwuSw0KZW5kc3RyZWFtDWVuZG9iag0xNiAwIG9iag08PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDE5Pj5zdHJlYW0NCkiJamAAARYGJgYegAADAAWxAJMNCmVuZHN0cmVhbQ1lbmRvYmoNMTcgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aCA4MzMvU3VidHlwZS9DSURGb250VHlwZTBDPj5zdHJlYW0NCkiJfJNvbAxpHMdnrJldOtkNssJOO/Oc6HmhdDVEJdqca6yr5K5LtwhR2e5O11Aza2aUTe21VV39E4rdbWm3ehqUovW/ipKghBCNc8QSfxLu1b3leXRWmBlvJJJ7XnzyfJ7f83x/eZ7kwbGxYzAcx6cuKypY4SqY+Tsv8KLglsRZy7nAlgqvpBdnIRqlN1MMysDRlLGIoezqJTWVTsZGNxNvqWlokg1Nm4DSqczRMdR0jNACMRKzYl9wCs9Y5BfLuEI/Jyi8EioQgyGJD6xXwJwFC5xZOucYzDE41+B8g7lZIMfpdBrMMTgXGFmgOCQr3CYZFAo+UQqKklfh/LPBoooKYETLQOJkTqrUF7/dBvAy4HhlPScBr1YM8Np5ifMDRfL6uU1eaSMQ9cp3Wv4/rQAvAC0LlAi8bsWKtigDr+DP1lJEo4tP3CIoEs/Js7NdxZ5QkAO5wM+V//i22piHuTAPVoJ9G8bbLceu4pl4I/4YNTQPof+GcI3Th0yoYfInd6rhs9uMcj8xdjVfjar5MEogMnXDrs+gbindoGGqbkg3fadmVvS5uQe97sPPd0HfGxN6hyL2yHDkyaCjktxWVVcfpFMsKf65uzvMbiUbPZGlkSLLcbJtINrTlrB0H+iKvqLvpWrIhXW1znpGhOd7zFn76uJJB6p5bH6a2Cl3sG1VMal1jcWK8qofQc8FaDuDn0nC1W9NyPbBzge4Kh+9OO8WTG9iYVoLnBBP7LF0tuyNdjme//ZP7sqS4NoypqxU+sPlUIm/Z0Bb70hn8j6j5sEX9pun16xsYsP19SGmcZmnqZh+2T5wcZC2IlP1KfRTL357BNLPTPAJfG5vOFJzp67bEq0Mxsro7CL34vwHG+6K7JByXF7n8PJieVHp8MMQszlCBGJL9oeZ7Z2D267TL95c+XdkVf8vvWzpIV/3Zce5YyfOXuvzuQ8xVjhcfRt+OIe/T5rg9X77jqPEzrBSK9HShvaXLIx/NLft33N4R9yiEjCDDO9eWkj8utYcFFpqiRF1gFzY57sf62iJJRir/pnGIZb6+dSobeL2dlTY0XoQZh442N7fSqrxhJn5y7VrHTWumUo7OT6Z9lWAAQDiZX0IDQplbmRzdHJlYW0NZW5kb2JqDTE4IDAgb2JqDTw8L0ZpbHRlci9GbGF0ZURlY29kZS9MZW5ndGggMjUwPj5zdHJlYW0NCkiJXJDPisMgEMbvPsUc20MxbZP2EoTSUshh/7DZfQCjk6ywUTHmkLff0ZQu7IDCz/m+8WP4tbk11kTg78GpFiP0xuqAk5uDQuhwMJbtD6CNig/KtxqlZ5zM7TJFHBvbO1bXwD+oOcWwwOaiXYdbxt+CxmDsAJuva7sF3s7e/+CINkIBQoDGnga9SP8qRwSebbtGU9/EZUeeP8Xn4hEOmfdrGOU0Tl4qDNIOyOqCSkB9pxIMrf7XL1dX16tvGZL6WJG6KKpSJCpPmU5VJnpMdD6utCrPZZ77mJB+oEXAM76aQ6DkeVs5cgprLD4X6p0HcqXDfgUYAKZnd7cNCmVuZHN0cmVhbQ1lbmRvYmoNMSAwIG9iag08PC9GaWx0ZXIvRmxhdGVEZWNvZGUvRmlyc3QgMTQvTGVuZ3RoIDEyOC9OIDMvVHlwZS9PYmpTdG0+PnN0cmVhbQ0KaN4yUzBQMFcwsVSwULA0VrCx0XfOL80rUTDUd8ssKi4BShkoBOn7JMKZIZUFqfr+pSU5mXmpxXZ2QA2OQK0gmYDEolSgTjOIssySnFQNn9TUolSF4NTMklRNsFqXaENjsHxEZBTIYksjhbzSnJxY/WB99/yQfDs7gAADANjdJ7kNCmVuZHN0cmVhbQ1lbmRvYmoNMiAwIG9iag08PC9MZW5ndGggMzIwNi9TdWJ0eXBlL1hNTC9UeXBlL01ldGFkYXRhPj5zdHJlYW0NCjw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDcuMC1jMDAwIDc5LjEzNTdjOWUsIDIwMjEvMDcvMTQtMDA6Mzk6NTYgICAgICAgICI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgICAgICAgICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgICAgICAgICB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIKICAgICAgICAgICAgeG1sbnM6cGRmPSJodHRwOi8vbnMuYWRvYmUuY29tL3BkZi8xLjMvIj4KICAgICAgICAgPHhtcDpNb2RpZnlEYXRlPjIwMjItMDEtMDdUMTU6MjU6NDErMDE6MDA8L3htcDpNb2RpZnlEYXRlPgogICAgICAgICA8eG1wOkNyZWF0ZURhdGU+MjAyMi0wMS0wN1QxMTozMzozNyswMTowMDwveG1wOkNyZWF0ZURhdGU+CiAgICAgICAgIDx4bXA6TWV0YWRhdGFEYXRlPjIwMjItMDEtMDdUMTU6MjU6NDErMDE6MDA8L3htcDpNZXRhZGF0YURhdGU+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+QWRvYmUgQWNyb2JhdCBQcm8gREMgKDMyLWJpdCkgMjEuNy4yMDA5OTwveG1wOkNyZWF0b3JUb29sPgogICAgICAgICA8ZGM6Zm9ybWF0PmFwcGxpY2F0aW9uL3BkZjwvZGM6Zm9ybWF0PgogICAgICAgICA8eG1wTU06RG9jdW1lbnRJRD51dWlkOmFkZmExOGVjLTA0NzctNDczZS1hN2FlLTc0NDVjOGY4ZGIwNTwveG1wTU06RG9jdW1lbnRJRD4KICAgICAgICAgPHhtcE1NOkluc3RhbmNlSUQ+dXVpZDo0NzBiYzAxZi02ZjliLTQzOWUtYWU3Yi02NjFkNjA1NGUxN2Q8L3htcE1NOkluc3RhbmNlSUQ+CiAgICAgICAgIDxwZGY6UHJvZHVjZXI+QWRvYmUgQWNyb2JhdCBQcm8gREMgKDMyLWJpdCkgMjEuNy4yMDA5OTwvcGRmOlByb2R1Y2VyPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgIAo8P3hwYWNrZXQgZW5kPSJ3Ij8+DQplbmRzdHJlYW0NZW5kb2JqDTMgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0ZpcnN0IDQvTGVuZ3RoIDQ5L04gMS9UeXBlL09ialN0bT4+c3RyZWFtDQpo3rJUMFCwsdF3zi/NK1Ew1PfOTCmONjQGCgbF6odUFqTqBySmpxbb2QEEGADgNQuvDQplbmRzdHJlYW0NZW5kb2JqDTQgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0ZpcnN0IDUvTGVuZ3RoIDEyNS9OIDEvVHlwZS9PYmpTdG0+PnN0cmVhbQ0KaN6UzLEKwjAURuFXuVsTxPa/N5ZQKYXSrIIP0KVpMnTxQojvryA4uLmf8zEINI7dUvJWD32ErWYTrgIRMDyzc86fwA3Q2E+lxcxJY6Z5Lxq3SveiFBZajZNzPOpqSbj1rQDDYLubpl+0l/7CX/S9p+ee/1Kn6SXAAB97MaENCmVuZHN0cmVhbQ1lbmRvYmoNNSAwIG9iag08PC9EZWNvZGVQYXJtczw8L0NvbHVtbnMgNC9QcmVkaWN0b3IgMTI+Pi9GaWx0ZXIvRmxhdGVEZWNvZGUvSURbPDQ2ODlCNzBDRDZENjk2NENCMjMxREI5NTY0RkYwRDUxPjw1N0RCODQ3MTg1RUE3NDQxOTI0QzA0NkExQTFFNzQ5Nz5dL0luZm8gMTAgMCBSL0xlbmd0aCA0Ny9Sb290IDEyIDAgUi9TaXplIDExL1R5cGUvWFJlZi9XWzEgMiAxXT4+c3RyZWFtDQpo3mJiAAImRtFeBiYGxntAgvcykGAAc28BJe7EgLgMjDCC6R+QYGQACDAAsHAGHQ0KZW5kc3RyZWFtDWVuZG9iag1zdGFydHhyZWYNCjExNg0KJSVFT0YNCg==";
    final segments = [
      AnswerSegment(
          start: SegmentPosition(page: 1, y: 0),
          end: SegmentPosition(page: 2, y: 0))
    ];

    final answers = exam.tasks
        .map((e) => Answer(
            task: Task(id: e.id, title: e.title, maxPoints: e.maxPoints),
            segments: segments,
            achievedPoints: 0,
            status: CorrectableStatus.pending))
        .toList(growable: false);

    return exam
        .getParticipants()
        .map((e) => Submission(
            id: "$examId _ ${e.id}",
            exam: exam,
            student: Student(id: e.id, displayName: e.displayName),
            data: pdf1,
            answers: answers,
            achievedPoints: 0,
            status: CorrectableStatus.pending))
        .toList(growable: false);
  }
}
